sudo: required
services:
    - docker

#before_install:

script:
    #after_success:
    - docker build -t $DOCKER_ID/mcnt-uix ./uix
    - docker build -t $DOCKER_ID/mcnt-api ./api
    - docker build -t $DOCKER_ID/mcnt-nginx ./nginx
    - docker build -t $DOCKER_ID/mcnt-worker ./worker
    - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push $DOCKER_ID/mcnt-uix
    - docker push $DOCKER_ID/mcnt-api
    - docker push $DOCKER_ID/mcnt-nginx
    - docker push $DOCKER_ID/mcnt-worker
