version: '3'
services:
    nginx:
        build:
            context: ./nginx
        ports:
            - '8555:80'
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
            - PGDATA=/var/lib/postgresql/data/pgdata
    redis:
        image: 'redis:latest'
    api:
        build: 
            context: ./api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWD=postgres_password
            - PGPORT=5432
    worker:
        build:
            context: ./worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    uix:
        build:
            context: ./uix
